---
driver:
  name: vagrant

provisioner:
  name: shell

platforms:
  - name: vbox/redis64
    driver:
      box: redis64
      provider: virtualbox
 
verifier:
  name: inspec

suites:
  - name: default
