---
driver:
  name: vagrant

provisioner:
  name: shell

platforms:
  - name: vbox/redis-server
    driver:
      box: redis-server
      provider: virtualbox
 
verifier:
  name: inspec

suites:
  - name: default
